version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      timezone: Asia/Yekaterinburg
    reviewers:
      - VChet
    open-pull-requests-limit: 10
    labels:
      - dependency
