name: Build

on:
  push:
    branch: master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install pnpm
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          cache: true

      - name: Audit dependencies
        run: pnpm audit --prod --audit-level=high

      - name: Run linters
        run: node --run lint:all

      - name: Run build
        run: node --run generate all
